greeting1 = Greeting.create(text: 'How do you do?')
greeting2 = Greeting.create(text: 'Nice to meet you')
greeting3 = Greeting.create(text: 'How have you been?')
greeting4 = Greeting.create(text: 'Hello')
greeting5 = Greeting.create(text: 'How are you doing?')
